{% set name = "plotmol" %}
{% set version = "0.0.3" %}
{% set sha256 = "434078c293b20887f131f9be667a351d754fc7b9eb750e0c20c276e48d65afe4" %}

package:
  name: plotmol
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - rdkit
    - bokeh

test:
  imports:
    - plotmol

about:
  home: https://github.com/SimonBoothroyd/plotmol
  license: MIT
  license_file: LICENSE
  description: Interactive plotting of data annotated with molecule structures.

extra:
  recipe-maintainers:
    - simonboothroyd
